package com.legendshop.core.constant;

public enum ConfigPropertiesEnum {
	LEGENDSHOP_SYSTEM_ID, LEGENDSHOP_VERSION, INSTALLED, SQL_DEBUG_MODE, LUCENE_PATH, BIG_PIC_PATH, SMALL_PIC_PATH, BACKUP_PIC_PATH, DOWNLOAD_PATH, CURRENCY_PATTERN, BUSINESS_MODE, LANGUAGE_MODE, SYSTEM_CONFIG, HTML_PATH;
}